using System;
using System.Data;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using CAL_QR.Models;

namespace CAL_QR.Data
{
    public static class DatabaseMigrator
    {
        public static void RunMigrations(CalQrDbContext context)
        {
            // First, make sure the database is created
            context.Database.EnsureCreated();

            if (context.Database.IsRelational())
            {
                // Enable Write-Ahead Logging (WAL) and set Busy Timeout
                context.Database.ExecuteSqlRaw("PRAGMA journal_mode=WAL;");
                context.Database.ExecuteSqlRaw("PRAGMA busy_timeout=5000;");

                // Create AcknowledgedExpiredDevices table if it doesn't exist
                context.Database.ExecuteSqlRaw(@"
                    CREATE TABLE IF NOT EXISTS AcknowledgedExpiredDevices (
                        Id INTEGER PRIMARY KEY AUTOINCREMENT,
                        DeviceId INTEGER NOT NULL,
                        CalibrationRecordId INTEGER NOT NULL,
                        AcknowledgedDate TEXT NOT NULL
                    );
                ");

                // Create Users table if it doesn't exist
                context.Database.ExecuteSqlRaw(@"
                    CREATE TABLE IF NOT EXISTS Users (
                        Id INTEGER PRIMARY KEY AUTOINCREMENT,
                        Username TEXT NOT NULL UNIQUE,
                        PasswordHash TEXT NOT NULL,
                        FullName TEXT NOT NULL,
                        Role INTEGER NOT NULL,
                        Permissions INTEGER NOT NULL,
                        IsEditor INTEGER NOT NULL,
                        IsActive INTEGER NOT NULL DEFAULT 1,
                        CreatedAt TEXT NOT NULL,
                        LastLoginAt TEXT,
                        FailedLoginAttempts INTEGER NOT NULL DEFAULT 0,
                        LockedUntil TEXT
                    );
                ");

                // Execute defensive migrations for AuditLogs
                ExecuteSqlIfColumnMissing(context, "AuditLogs", "UserId", "ALTER TABLE AuditLogs ADD COLUMN UserId INTEGER;");
                ExecuteSqlIfColumnMissing(context, "AuditLogs", "Username", "ALTER TABLE AuditLogs ADD COLUMN Username TEXT;");

                // Execute defensive migrations for PaperTemplates
                ExecuteSqlIfColumnMissing(context, "PaperTemplates", "MarginRightMm", "ALTER TABLE PaperTemplates ADD COLUMN MarginRightMm TEXT DEFAULT '0' NOT NULL;");
                ExecuteSqlIfColumnMissing(context, "PaperTemplates", "MarginBottomMm", "ALTER TABLE PaperTemplates ADD COLUMN MarginBottomMm TEXT DEFAULT '0' NOT NULL;");

                // Execute defensive migrations for IsSeedTestData column
                ExecuteSqlIfColumnMissing(context, "Owners", "IsSeedTestData", "ALTER TABLE Owners ADD COLUMN IsSeedTestData INTEGER DEFAULT 0 NOT NULL;");
                ExecuteSqlIfColumnMissing(context, "Devices", "IsSeedTestData", "ALTER TABLE Devices ADD COLUMN IsSeedTestData INTEGER DEFAULT 0 NOT NULL;");
                ExecuteSqlIfColumnMissing(context, "CalibrationRecords", "IsSeedTestData", "ALTER TABLE CalibrationRecords ADD COLUMN IsSeedTestData INTEGER DEFAULT 0 NOT NULL;");

                // Execute defensive migrations for the Certificate tables.
                // EnsureCreated() is a no-op on a pre-existing database, so these tables would never
                // be created on an installed system. The statements below are copied verbatim from
                // the script generated by EF Core (Database.GenerateCreateScript) for these entities.
                // Order matters: Certificates first, the three child tables reference it.
                ExecuteSqlIfTableMissing(context, "Certificates", @"
                    CREATE TABLE ""Certificates"" (
                        ""Id"" INTEGER NOT NULL CONSTRAINT ""PK_Certificates"" PRIMARY KEY AUTOINCREMENT,
                        ""CalibrationRecordId"" INTEGER NOT NULL,
                        ""CertificateNumber"" TEXT NOT NULL,
                        ""ReferenceNo"" TEXT NULL,
                        ""ClientName"" TEXT NOT NULL,
                        ""ClientAddress"" TEXT NULL,
                        ""DeviceModel"" TEXT NOT NULL,
                        ""DeviceSerialNumber"" TEXT NOT NULL,
                        ""DeviceManufacturer"" TEXT NULL,
                        ""SurveyMeterModel"" TEXT NULL,
                        ""SurveyMeterSerialNumber"" TEXT NULL,
                        ""MeasurementType"" TEXT NULL,
                        ""Distance"" TEXT NULL,
                        ""CountingTime"" TEXT NULL,
                        ""CountingUnit"" TEXT NULL,
                        ""Temperature"" TEXT NULL,
                        ""RelativeHumidity"" TEXT NULL,
                        ""AtmosphericPressure"" TEXT NULL,
                        ""CorrectedReadingFormula"" TEXT NULL,
                        ""ComplianceVerdict"" TEXT NULL,
                        ""CalibrationStandard"" TEXT NULL,
                        ""MethodologyEnabled"" INTEGER NOT NULL,
                        ""RadiationSource"" TEXT NULL,
                        ""ReferenceGeometry"" TEXT NULL,
                        ""MethodologyText"" TEXT NULL,
                        ""TraceabilityReference"" TEXT NULL,
                        ""UncertaintyEnabled"" INTEGER NOT NULL,
                        ""CombinedUncertainty"" TEXT NULL,
                        ""ExpandedUncertainty"" TEXT NULL,
                        ""CoverageFactor"" TEXT NULL,
                        ""AdditionalInformation"" TEXT NULL,
                        ""Notes"" TEXT NULL,
                        ""QrPayload"" TEXT NULL,
                        ""QrPayloadVersion"" TEXT NULL,
                        ""CalibratedByName"" TEXT NULL,
                        ""CalibratedByTitle"" TEXT NULL,
                        ""CalibratedByDate"" TEXT NULL,
                        ""ReviewedByName"" TEXT NULL,
                        ""ReviewedByTitle"" TEXT NULL,
                        ""ReviewedByDate"" TEXT NULL,
                        ""ApprovedByName"" TEXT NULL,
                        ""ApprovedByTitle"" TEXT NULL,
                        ""ApprovedByDate"" TEXT NULL,
                        ""AuthorizedByName"" TEXT NULL,
                        ""AuthorizedByTitle"" TEXT NULL,
                        ""AuthorizedByDate"" TEXT NULL,
                        ""CertificateTemplateType"" TEXT NULL,
                        ""ProcedureNo"" TEXT NULL,
                        ""CalibrationLocation"" TEXT NULL,
                        ""Instrumentation"" TEXT NULL,
                        ""DetectorType"" TEXT NULL,
                        ""CalibrationDate"" TEXT NULL,
                        ""IssueDate"" TEXT NULL,
                        ""DueDate"" TEXT NULL,
                        ""VerifyCode"" TEXT NULL,
                        ""SignaturePayloadVersion"" TEXT NULL,
                        ""FirstPrintedAt"" TEXT NULL,
                        ""AmendedAt"" TEXT NULL,
                        ""IssuedAt"" TEXT NOT NULL,
                        ""IsDeleted"" INTEGER NOT NULL,
                        ""CreatedAt"" TEXT NOT NULL,
                        ""UpdatedAt"" TEXT NOT NULL,
                        CONSTRAINT ""FK_Certificates_CalibrationRecords_CalibrationRecordId"" FOREIGN KEY (""CalibrationRecordId"") REFERENCES ""CalibrationRecords"" (""Id"") ON DELETE RESTRICT
                    );
                ");

                ExecuteSqlIfTableMissing(context, "CertificateCalibrationResults", @"
                    CREATE TABLE ""CertificateCalibrationResults"" (
                        ""Id"" INTEGER NOT NULL CONSTRAINT ""PK_CertificateCalibrationResults"" PRIMARY KEY AUTOINCREMENT,
                        ""CertificateId"" INTEGER NOT NULL,
                        ""SortOrder"" INTEGER NOT NULL,
                        ""SourceId"" TEXT NULL,
                        ""Radionuclide"" TEXT NULL,
                        ""Scale"" TEXT NULL,
                        ""ReferenceDoseLevel"" TEXT NULL,
                        ""ReferenceValue"" TEXT NULL,
                        ""MeasuredReading"" TEXT NULL,
                        ""CorrectionFactor"" TEXT NULL,
                        ""RelativeError"" TEXT NULL,
                        ""AbsoluteRelativeError"" TEXT NULL,
                        ""Unit"" TEXT NULL,
                        ""Remarks"" TEXT NULL,
                        CONSTRAINT ""FK_CertificateCalibrationResults_Certificates_CertificateId"" FOREIGN KEY (""CertificateId"") REFERENCES ""Certificates"" (""Id"") ON DELETE CASCADE
                    );
                ");

                ExecuteSqlIfTableMissing(context, "CertificateUncertaintyComponents", @"
                    CREATE TABLE ""CertificateUncertaintyComponents"" (
                        ""Id"" INTEGER NOT NULL CONSTRAINT ""PK_CertificateUncertaintyComponents"" PRIMARY KEY AUTOINCREMENT,
                        ""CertificateId"" INTEGER NOT NULL,
                        ""SortOrder"" INTEGER NOT NULL,
                        ""ComponentName"" TEXT NOT NULL,
                        ""EvaluationType"" TEXT NULL,
                        ""StandardUncertainty"" TEXT NULL,
                        ""ContributionPercent"" TEXT NULL,
                        ""Distribution"" TEXT NULL,
                        CONSTRAINT ""FK_CertificateUncertaintyComponents_Certificates_CertificateId"" FOREIGN KEY (""CertificateId"") REFERENCES ""Certificates"" (""Id"") ON DELETE CASCADE
                    );
                ");

                ExecuteSqlIfTableMissing(context, "CertificateFunctionalChecks", @"
                    CREATE TABLE ""CertificateFunctionalChecks"" (
                        ""Id"" INTEGER NOT NULL CONSTRAINT ""PK_CertificateFunctionalChecks"" PRIMARY KEY AUTOINCREMENT,
                        ""CertificateId"" INTEGER NOT NULL,
                        ""SortOrder"" INTEGER NOT NULL,
                        ""CheckName"" TEXT NOT NULL,
                        ""Requirement"" TEXT NULL,
                        ""Result"" TEXT NULL,
                        ""Remarks"" TEXT NULL,
                        CONSTRAINT ""FK_CertificateFunctionalChecks_Certificates_CertificateId"" FOREIGN KEY (""CertificateId"") REFERENCES ""Certificates"" (""Id"") ON DELETE CASCADE
                    );
                ");

                // Defensive migrations for the columns discovered in the Beta Scintillation Probe,
                // PED and Dose Rate Meter certificate forms. The CREATE TABLE statements above cover
                // databases created from now on; these ALTER statements cover databases where the
                // Certificate tables already exist without these columns. Without them the first
                // query against Certificates fails with "no such column".
                ExecuteSqlIfColumnMissing(context, "Certificates", "MeasurementType", "ALTER TABLE Certificates ADD COLUMN MeasurementType TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "Certificates", "Distance", "ALTER TABLE Certificates ADD COLUMN Distance TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "Certificates", "CountingTime", "ALTER TABLE Certificates ADD COLUMN CountingTime TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "Certificates", "CountingUnit", "ALTER TABLE Certificates ADD COLUMN CountingUnit TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "Certificates", "CalibrationStandard", "ALTER TABLE Certificates ADD COLUMN CalibrationStandard TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "CertificateCalibrationResults", "ReferenceDoseLevel", "ALTER TABLE CertificateCalibrationResults ADD COLUMN ReferenceDoseLevel TEXT NULL;");

                // البنية التحتية لميزة الشهادة — المرحلة ١.
                // كلها TEXT NULL: SQLite لا يقبل ADD COLUMN NOT NULL بلا قيمة افتراضية.
                ExecuteSqlIfColumnMissing(context, "Certificates", "CertificateTemplateType", "ALTER TABLE Certificates ADD COLUMN CertificateTemplateType TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "Certificates", "CalibrationDate", "ALTER TABLE Certificates ADD COLUMN CalibrationDate TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "Certificates", "IssueDate", "ALTER TABLE Certificates ADD COLUMN IssueDate TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "Certificates", "DueDate", "ALTER TABLE Certificates ADD COLUMN DueDate TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "Certificates", "VerifyCode", "ALTER TABLE Certificates ADD COLUMN VerifyCode TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "Certificates", "SignaturePayloadVersion", "ALTER TABLE Certificates ADD COLUMN SignaturePayloadVersion TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "Certificates", "FirstPrintedAt", "ALTER TABLE Certificates ADD COLUMN FirstPrintedAt TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "Certificates", "AmendedAt", "ALTER TABLE Certificates ADD COLUMN AmendedAt TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "CertificateCalibrationResults", "RelativeError", "ALTER TABLE CertificateCalibrationResults ADD COLUMN RelativeError TEXT NULL;");

                // التعبئة الرجعية للتواريخ الثلاثة — جزء إلزامي من الهجرة لا تحسين.
                // الأعمدة تُضاف NULL بحكم قيد SQLite، بينما هي DateTime غير قابل
                // للعدم في الكيان: قراءة NULL فيها تُلقي استثناءً عند أول استعلام.
                // AmendedAt و FirstPrintedAt و VerifyCode تبقى NULL — دلالتها الصحيحة
                // «لم يحدث بعد»، وهي nullable في الكيان أصلاً.
                // ملاحظة مسجَّلة: date(IssuedAt) يقرأ التاريخ بتوقيت UTC، فشهادة
                // أُصدرت بعد الساعة 22:00 بتوقيت ليبيا تُعبَّأ بتاريخ اليوم السابق.
                // غير مؤثر عملياً: لا توجد شهادات صادرة في أي قاعدة، فهذه الجملة
                // لن تلمس صفاً واحداً. تُسجَّل هنا كي لا تُكتشف كعطل لاحقاً.
                context.Database.ExecuteSqlRaw(@"
                    UPDATE Certificates SET IssueDate = date(IssuedAt) WHERE IssueDate IS NULL;");
                context.Database.ExecuteSqlRaw(@"
                    UPDATE Certificates SET CalibrationDate = (
                        SELECT date(cr.CalibrationDate) FROM CalibrationRecords cr
                        WHERE cr.Id = Certificates.CalibrationRecordId)
                    WHERE CalibrationDate IS NULL;");
                context.Database.ExecuteSqlRaw(@"
                    UPDATE Certificates SET DueDate = date(CalibrationDate, '+1 year')
                    WHERE DueDate IS NULL AND CalibrationDate IS NOT NULL;");

                // عدّاد أرقام الشهادات. Year مفتاح أساسي ⇒ فهرس فريد مجاني
                // ⇒ استحالة صفّين لسنة واحدة على مستوى المحرّك.
                context.Database.ExecuteSqlRaw(@"
                    CREATE TABLE IF NOT EXISTS CertificateSequence (
                        Year       INTEGER NOT NULL PRIMARY KEY,
                        LastNumber INTEGER NOT NULL DEFAULT 0
                    );
                ");

                // أرشيف رموز التحقق المستبدلة بعد تعديل شهادة.
                context.Database.ExecuteSqlRaw(@"
                    CREATE TABLE IF NOT EXISTS CertificateVerifyCodeHistory (
                        Id                      INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                        CertificateId           INTEGER NOT NULL,
                        VerifyCode              TEXT    NOT NULL,
                        SignaturePayloadVersion TEXT    NULL,
                        ReplacedAt              TEXT    NOT NULL,
                        CONSTRAINT FK_CertificateVerifyCodeHistory_Certificates_CertificateId
                            FOREIGN KEY (CertificateId) REFERENCES Certificates (Id) ON DELETE CASCADE
                    );
                ");

                // ── المرحلة ٢: مكتبة الحقول والقوالب ──

                // أعمدة الشهادة الأربعة (Pancake و PED)
                ExecuteSqlIfColumnMissing(context, "Certificates", "ProcedureNo", "ALTER TABLE Certificates ADD COLUMN ProcedureNo TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "Certificates", "CalibrationLocation", "ALTER TABLE Certificates ADD COLUMN CalibrationLocation TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "Certificates", "Instrumentation", "ALTER TABLE Certificates ADD COLUMN Instrumentation TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "Certificates", "DetectorType", "ALTER TABLE Certificates ADD COLUMN DetectorType TEXT NULL;");

                // أعمدة قالب الشهادة على DeviceTypes
                ExecuteSqlIfColumnMissing(context, "DeviceTypes", "ProcedureNo", "ALTER TABLE DeviceTypes ADD COLUMN ProcedureNo TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "DeviceTypes", "CalibrationLocation", "ALTER TABLE DeviceTypes ADD COLUMN CalibrationLocation TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "DeviceTypes", "ReferenceGeometry", "ALTER TABLE DeviceTypes ADD COLUMN ReferenceGeometry TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "DeviceTypes", "CountingTime", "ALTER TABLE DeviceTypes ADD COLUMN CountingTime TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "DeviceTypes", "CountingUnit", "ALTER TABLE DeviceTypes ADD COLUMN CountingUnit TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "DeviceTypes", "MethodologyText", "ALTER TABLE DeviceTypes ADD COLUMN MethodologyText TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "DeviceTypes", "TraceabilityReference", "ALTER TABLE DeviceTypes ADD COLUMN TraceabilityReference TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "DeviceTypes", "ComplianceVerdict", "ALTER TABLE DeviceTypes ADD COLUMN ComplianceVerdict TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "DeviceTypes", "CalibrationStandard", "ALTER TABLE DeviceTypes ADD COLUMN CalibrationStandard TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "DeviceTypes", "Notes", "ALTER TABLE DeviceTypes ADD COLUMN Notes TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "DeviceTypes", "AdditionalInformation", "ALTER TABLE DeviceTypes ADD COLUMN AdditionalInformation TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "DeviceTypes", "MeasurementType", "ALTER TABLE DeviceTypes ADD COLUMN MeasurementType TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "DeviceTypes", "Distance", "ALTER TABLE DeviceTypes ADD COLUMN Distance TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "DeviceTypes", "CorrectedReadingFormula", "ALTER TABLE DeviceTypes ADD COLUMN CorrectedReadingFormula TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "DeviceTypes", "DetectorType", "ALTER TABLE DeviceTypes ADD COLUMN DetectorType TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "DeviceTypes", "Instrumentation", "ALTER TABLE DeviceTypes ADD COLUMN Instrumentation TEXT NULL;");
                ExecuteSqlIfColumnMissing(context, "DeviceTypes", "UncertaintyEnabled", "ALTER TABLE DeviceTypes ADD COLUMN UncertaintyEnabled INTEGER NOT NULL DEFAULT 0;");
                ExecuteSqlIfColumnMissing(context, "DeviceTypes", "MethodologyEnabled", "ALTER TABLE DeviceTypes ADD COLUMN MethodologyEnabled INTEGER NOT NULL DEFAULT 0;");

                // ملخّص النويدات — الطبقة الوسطى بين قراءات المصادر والملصق
                context.Database.ExecuteSqlRaw(@"
                    CREATE TABLE IF NOT EXISTS CertificateNuclideSummaries (
                        Id                      INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                        CertificateId           INTEGER NOT NULL,
                        SortOrder               INTEGER NOT NULL,
                        Radionuclide            TEXT    NOT NULL,
                        AverageCorrectionFactor TEXT    NULL,
                        CONSTRAINT FK_CertificateNuclideSummaries_Certificates_CertificateId
                            FOREIGN KEY (CertificateId) REFERENCES Certificates (Id) ON DELETE CASCADE
                    );
                ");

                // جدولا القوالب على مستوى نوع الجهاز
                context.Database.ExecuteSqlRaw(@"
                    CREATE TABLE IF NOT EXISTS DeviceTypeFunctionalCheckTemplates (
                        Id            INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                        DeviceTypeId  INTEGER NOT NULL,
                        SortOrder     INTEGER NOT NULL,
                        CheckName     TEXT    NOT NULL,
                        Requirement   TEXT    NULL,
                        DefaultResult TEXT    NULL,
                        CONSTRAINT FK_DeviceTypeFunctionalCheckTemplates_DeviceTypes_DeviceTypeId
                            FOREIGN KEY (DeviceTypeId) REFERENCES DeviceTypes (Id) ON DELETE CASCADE
                    );
                ");

                context.Database.ExecuteSqlRaw(@"
                    CREATE TABLE IF NOT EXISTS DeviceTypeUncertaintyComponentTemplates (
                        Id                  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                        DeviceTypeId        INTEGER NOT NULL,
                        SortOrder           INTEGER NOT NULL,
                        ComponentName       TEXT    NOT NULL,
                        EvaluationType      TEXT    NULL,
                        StandardUncertainty TEXT    NULL,
                        ContributionPercent TEXT    NULL,
                        Distribution        TEXT    NULL,
                        CONSTRAINT FK_DeviceTypeUncertaintyComponentTemplates_DeviceTypes_DeviceTypeId
                            FOREIGN KEY (DeviceTypeId) REFERENCES DeviceTypes (Id) ON DELETE CASCADE
                    );
                ");

                // إسقاط Certificate.AverageCorrectionFactor — استبدله جدول
                // CertificateNuclideSummaries، لأن الحقل المفرد يعجز عن تمثيل
                // أكثر من نويدة واحدة.
                //
                // إسقاط فعلي لا هجر: SQLite المرفق مع SQLitePCLRaw 2.1.6 هو 3.44+،
                // و DROP COLUMN مدعوم منذ 3.35.0. الإصدار مثبَّت بمرجع الحزمة لا
                // بنظام المستخدم، فالسلوك حتمي. والعمود غير مفهرس وغير داخل أي
                // قيد، وهما الحالتان الوحيدتان اللتان يرفض فيهما SQLite الإسقاط.
                // ولا شهادات صادرة، فصفر فقد بيانات.
                //
                // الترتيب ملزم: بعد كل ALTER … ADD وقبل إنشاء الفهارس.
                ExecuteSqlIfColumnExists(context, "Certificates", "AverageCorrectionFactor",
                    "ALTER TABLE Certificates DROP COLUMN AverageCorrectionFactor;");

                // Certificate indexes. IX_Certificates_CalibrationRecordId is a partial unique index:
                // it forbids two live certificates for one calibration record, yet still allows issuing
                // a replacement after the first one has been soft-deleted.
                // IX_Certificates_CertificateNumber is unconditionally unique on purpose — ISO/IEC 17025
                // forbids reusing a certificate number that was issued, even if it was later cancelled.
                context.Database.ExecuteSqlRaw(@"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Certificates_CertificateNumber"" ON ""Certificates"" (""CertificateNumber"");");
                context.Database.ExecuteSqlRaw(@"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Certificates_CalibrationRecordId"" ON ""Certificates"" (""CalibrationRecordId"") WHERE ""IsDeleted"" = 0;");
                context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_Certificates_IsDeleted"" ON ""Certificates"" (""IsDeleted"");");
                context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_Certificates_IssuedAt"" ON ""Certificates"" (""IssuedAt"");");
                context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_CertificateCalibrationResults_CertificateId"" ON ""CertificateCalibrationResults"" (""CertificateId"");");
                context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_CertificateUncertaintyComponents_CertificateId"" ON ""CertificateUncertaintyComponents"" (""CertificateId"");");
                context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_CertificateFunctionalChecks_CertificateId"" ON ""CertificateFunctionalChecks"" (""CertificateId"");");

                // فهارس البحث بالرمز. غير فريدة عمداً: تصادم رمز ١٦ خانة ممكن
                // نظرياً، وفهرس فريد كان سيُسقِط عملية إصدار أو تعديل مشروعة.
                context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_Certificates_VerifyCode"" ON ""Certificates"" (""VerifyCode"");");
                context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_CertificateVerifyCodeHistory_VerifyCode"" ON ""CertificateVerifyCodeHistory"" (""VerifyCode"");");
                context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_CertificateVerifyCodeHistory_CertificateId"" ON ""CertificateVerifyCodeHistory"" (""CertificateId"");");

                // فهارس المرحلة ٢
                context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_CertificateNuclideSummaries_CertificateId"" ON ""CertificateNuclideSummaries"" (""CertificateId"");");
                context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_DeviceTypeFunctionalCheckTemplates_DeviceTypeId"" ON ""DeviceTypeFunctionalCheckTemplates"" (""DeviceTypeId"");");
                context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_DeviceTypeUncertaintyComponentTemplates_DeviceTypeId"" ON ""DeviceTypeUncertaintyComponentTemplates"" (""DeviceTypeId"");");
            }

            // Perform any safe check/migration of columns if they are missing
            // e.g. ExecuteSqlIfColumnMissing(context, "TableName", "ColumnName", "ALTER TABLE TableName ADD COLUMN ColumnName TYPE;");
            
            // Seed default settings if they don't exist
            SeedDefaultSettings(context);

            // Seed default admin user if no users exist (under upgrade condition)
            SeedDefaultAdminUser(context);

            // بذر الأنواع الخمسة وقوالبها من DeviceTypeCatalog — مرة واحدة،
            // محروسة بعلم في AppSettings، ولا تدهس تعديلات المستخدم.
            //
            // الحصيلة تُكتب داخلياً في AppSettings تحت ConflictsKey أو FailureKey
            // ولا تُهمل هنا: إهمالها كان يُمرّر تعارض التسمية بصمت تام.
            // عرضها للمدير عند الإقلاع بند حاجز مسجَّل في القسم 10.0 من ملف القرارات.
            //
            // SeedIfNeeded لا تُصعِّد استثناءً أبداً — انظر تعليقها. فلا حاجة إلى
            // معالج هنا، والحارس داخلها لا في موضع الاستدعاء كي يشمل أي مستدعٍ آخر.
            var seedResult = DeviceTypeSeeder.SeedIfNeeded(context);
            if (seedResult.HasDiagnostics)
            {
                // ⚠ Debug.WriteLine يختفي في Release: هذا سطر مساعدة للمطوّر لا
                // مسار إبلاغ. المعوَّل عليه هو التسجيل الدائم في AppSettings،
                // وعرضه للمدير هو البند الحاجز رقم ٧.
                System.Diagnostics.Debug.WriteLine(
                    "[DeviceTypeSeeder] حصيلة تستحق العرض:\n" + seedResult.ToDiagnosticsText());
            }

            // One-time migration for splitting CertificateManagement (Records) to Verification, Owners, and DeviceTypes
            try
            {
                var migrationCompletedSetting = context.AppSettings.FirstOrDefault(s => s.Key == "PermissionsSplitMigrated_v1");
                if (migrationCompletedSetting == null || migrationCompletedSetting.Value != "true")
                {
                    var users = context.Users.ToList();
                    foreach (var user in users)
                    {
                        if (user.Permissions.HasFlag(SystemPermissions.Records))
                        {
                            user.Permissions |= SystemPermissions.Verification | 
                                                SystemPermissions.Owners | 
                                                SystemPermissions.DeviceTypes;
                        }
                    }

                    if (migrationCompletedSetting == null)
                    {
                        context.AppSettings.Add(new AppSetting { Key = "PermissionsSplitMigrated_v1", Value = "true" });
                    }
                    else
                    {
                        migrationCompletedSetting.Value = "true";
                    }
                    context.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"[DatabaseMigrator Error] Permissions split migration failed: {ex.Message}");
            }

            if (context.Database.IsRelational())
            {
                // Sync DatabasePath key in AppSettings with the active database connection DataSource
                try
                {
                    var connectionString = context.Database.GetDbConnection().ConnectionString;
                    var builder = new Microsoft.Data.Sqlite.SqliteConnectionStringBuilder(connectionString);
                    var activeDbPath = System.IO.Path.GetFullPath(builder.DataSource);

                    var dbPathSetting = context.AppSettings.FirstOrDefault(s => s.Key == "DatabasePath");
                    if (dbPathSetting == null)
                    {
                        context.AppSettings.Add(new AppSetting { Key = "DatabasePath", Value = activeDbPath });
                        context.SaveChanges();
                    }
                    else if (string.IsNullOrWhiteSpace(dbPathSetting.Value) || System.IO.Path.GetFullPath(dbPathSetting.Value) != activeDbPath)
                    {
                        dbPathSetting.Value = activeDbPath;
                        context.SaveChanges();
                    }
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine($"[DatabaseMigrator Error] Syncing database path failed: {ex.Message}");
                }
            }
        }

        public static void ExecuteSqlIfColumnMissing(CalQrDbContext context, string tableName, string columnName, string alterTableSql)
        {
            var connection = context.Database.GetDbConnection();
            var alreadyOpen = connection.State == ConnectionState.Open;

            try
            {
                if (!alreadyOpen) connection.Open();

                using var command = connection.CreateCommand();
                command.CommandText = $"PRAGMA table_info({tableName});";
                
                bool columnExists = false;
                using (var reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        var name = reader["name"]?.ToString();
                        if (string.Equals(name, columnName, StringComparison.OrdinalIgnoreCase))
                        {
                            columnExists = true;
                            break;
                        }
                    }
                }

                if (!columnExists)
                {
                    using var alterCommand = connection.CreateCommand();
                    alterCommand.CommandText = alterTableSql;
                    alterCommand.ExecuteNonQuery();
                }
            }
            finally
            {
                if (!alreadyOpen) connection.Close();
            }
        }

        /// <summary>
        /// مرآة معكوسة لـ ExecuteSqlIfColumnMissing: تُنفّذ الجملة **إن كان** العمود
        /// موجوداً. تُستعمل للإسقاط، فتكون idempotent — التشغيل الثاني لا يفعل شيئاً
        /// ولا يُلقي استثناءً على عمود غير موجود.
        /// </summary>
        public static void ExecuteSqlIfColumnExists(CalQrDbContext context, string tableName, string columnName, string sql)
        {
            var connection = context.Database.GetDbConnection();
            var alreadyOpen = connection.State == ConnectionState.Open;

            try
            {
                if (!alreadyOpen) connection.Open();

                using var command = connection.CreateCommand();
                command.CommandText = $"PRAGMA table_info({tableName});";

                bool columnExists = false;
                using (var reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        var name = reader["name"]?.ToString();
                        if (string.Equals(name, columnName, StringComparison.OrdinalIgnoreCase))
                        {
                            columnExists = true;
                            break;
                        }
                    }
                }

                if (columnExists)
                {
                    using var executeCommand = connection.CreateCommand();
                    executeCommand.CommandText = sql;
                    executeCommand.ExecuteNonQuery();
                }
            }
            finally
            {
                if (!alreadyOpen) connection.Close();
            }
        }

        private static void ExecuteSqlIfTableMissing(CalQrDbContext context, string tableName, string createSql)
        {
            var connection = context.Database.GetDbConnection();
            var alreadyOpen = connection.State == ConnectionState.Open;

            try
            {
                if (!alreadyOpen) connection.Open();

                using var command = connection.CreateCommand();
                command.CommandText = $"SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='{tableName}';";

                bool tableExists = Convert.ToInt32(command.ExecuteScalar() ?? 0) > 0;

                if (!tableExists)
                {
                    using var createCommand = connection.CreateCommand();
                    createCommand.CommandText = createSql;
                    createCommand.ExecuteNonQuery();
                }
            }
            finally
            {
                if (!alreadyOpen) connection.Close();
            }
        }

        private static void SeedDefaultSettings(CalQrDbContext context)
        {
            var defaultSettings = new[]
            {
                new AppSetting { Key = "DatabasePath", Value = "" },
                new AppSetting { Key = "AttachmentsPath", Value = "" },
                new AppSetting { Key = "QrOutputPath", Value = "" },
                new AppSetting { Key = "BackupPath", Value = "" },
                new AppSetting { Key = "CloudBackupPath", Value = "" },
                new AppSetting { Key = "BackupSchedule", Value = "Daily" },
                new AppSetting { Key = "AlertDaysThreshold", Value = "30" },
                new AppSetting { Key = "AutoLockMinutes", Value = "10" },
                new AppSetting { Key = "DefaultTemplateId", Value = "0" },
                new AppSetting { Key = "PasswordHash", Value = "" },
                new AppSetting { Key = "LastPrinterName", Value = "" },
                new AppSetting { Key = "LastTemplateId", Value = "0" },
                new AppSetting { Key = "DateFormat", Value = "YYYY-MM-DD" },
                new AppSetting { Key = "Language", Value = "ar" },
                new AppSetting { Key = "FirstRunCompleted", Value = "" },
                new AppSetting { Key = "SecurityQuestion", Value = "" },
                new AppSetting { Key = "SecurityAnswer", Value = "" }
            };

            bool changed = false;
            foreach (var setting in defaultSettings)
            {
                // AppSettings query should be fast and standard
                var exists = context.AppSettings.Any(s => s.Key == setting.Key);
                if (!exists)
                {
                    context.AppSettings.Add(setting);
                    changed = true;
                }
            }

            if (changed)
            {
                context.SaveChanges();
            }
        }

        private static void SeedDefaultAdminUser(CalQrDbContext context)
        {
            try
            {
                var firstRunSetting = context.AppSettings.FirstOrDefault(s => s.Key == "FirstRunCompleted");
                bool isFirstRunCompleted = firstRunSetting != null && firstRunSetting.Value == "true";

                if (isFirstRunCompleted && !context.Users.Any())
                {
                    // Generate a random temporary password
                    string tempPassword = Guid.NewGuid().ToString("N").Substring(0, 10);
                    string passwordHash = BCrypt.Net.BCrypt.HashPassword(tempPassword);

                    var adminUser = new User
                    {
                        Username = "admin",
                        PasswordHash = passwordHash,
                        FullName = "مدير النظام الافتراضي",
                        Role = UserRole.Admin,
                        Permissions = SystemPermissions.Records |
                                      SystemPermissions.Verification |
                                      SystemPermissions.Owners |
                                      SystemPermissions.DeviceTypes |
                                      SystemPermissions.Reports |
                                      SystemPermissions.Settings |
                                      SystemPermissions.BackupRestore |
                                      SystemPermissions.UserManagement,
                        IsEditor = true,
                        IsActive = true,
                        CreatedAt = DateTime.UtcNow
                    };

                    context.Users.Add(adminUser);
                    context.SaveChanges();

                    string warningMsg = $@"
========================================================================
⚠️ [تحذير أمني] تم إنشاء حساب المسؤول الافتراضي بنجاح!
اسم المستخدم: admin
كلمة المرور المؤقتة: {tempPassword}
يرجى تسجيل الدخول وتغيير كلمة المرور فوراً لأسباب أمنية.
========================================================================
";
                    System.Diagnostics.Debug.WriteLine(warningMsg);
                    Console.WriteLine(warningMsg);
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"[DatabaseMigrator Error] Seeding admin user failed: {ex.Message}");
            }
        }
    }
}
