<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>CAL_QR.DemoData</RootNamespace>
    <AssemblyName>CAL-QR.DemoData</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CAL-QR\CAL-QR.csproj" />
  </ItemGroup>

</Project>
